theme: jekyll-theme-modernist
title: Probabilidad y variables aleatorias para ML con R y Python
description: Vamos a ver las bases de R y Python aplicado al mundo de las probabilidades y variables aleatoria para Machine Learning